.\" 
.\" missdepslist manual page.
.\" (C) 2025 by Petar Petrov <slackalaxy@gmail.com> 
.\"
.TH missdeps 1
.SH NAME
missdepslist \- Check for missing deps of all packages that are installed.
.SH SYNOPSIS
.PP
.B missdepslist
.SH DESCRIPTION

The \fBmissdepslist\fP script works similar to \fBmissdeps\fP(1),
but outputs a simple list of missing dependencies, easy to parse.

.SH OPTIONS
.TP
no options available

.SH EXAMPLES
.B
missdepslist
.PP
displays dependencies that are missing from the system:

.PP
.nf
.fam C
eudev
sqlite3

.fam T
.fi

.SH SEE ALSO
\fBmissdeps\fP(1), \fBprt\-get\fP(8), \fBports\fP(8), \fBrevdep\fP(1)

.SH AUTHOR

\fBmissdepslist\fP was written by Petar Petrov <slackalaxy@gmail.com> for CRUX.
