.\" 
.\" revlib manual page.
.\" (C) 2025 by Petar Petrov <slackalaxy@gmail.com> 
.\"
.TH revlib 1
.SH NAME
revlib \- Find which ports contain missing libraries needed by a package.
.SH SYNOPSIS
.PP
.B revlib
.SH DESCRIPTION

Unlike \fBrevdep\fP(1), which will tell you what packages need to be recompiled after
a \fBprt\-get sysup\fP(8), this small tool will report which ports contain the missing
libraries required by a certain package. It is handy, for example, on systems managed
by \fBpkg\-get\fP(8), where some packages might have linked to optional ports, not listed
at the \fB#Depends on:\fP line. The \fBports\fP(8) database (and hence .footprints)
should be updated for this to work properly.

.SH OPTIONS
.TP
no options available

.SH EXAMPLES
.TP
.B revlib port
outputs ports containing the missing libraries required by the installed \fBport\fP

.SH SEE ALSO
\fBrevdep\fP(1), \fBprt\-get\fP(8), \fBports\fP(8)

.SH AUTHOR

\fBrevlib\fP was written by Petar Petrov <slackalaxy@gmail.com> for CRUX.
